# Generated by Django 3.1.11 on 2021-05-24 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0004_auto_20210524_0924'),
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='item',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='currency',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='items.currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
