# Generated by Django 3.1.11 on 2021-05-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_auto_20210524_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_items',
            field=models.ManyToManyField(blank=True, to='inventories.InventoryItem'),
        ),
    ]
