# Generated by Django 3.1.11 on 2021-05-24 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_item_currency'),
        ('offers', '0002_auto_20210524_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseoffer',
            name='item',
        ),
        migrations.AddField(
            model_name='purchaseoffer',
            name='currency',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='items.currency'),
            preserve_default=False,
        ),
    ]
