# Generated by Django 3.1.11 on 2021-05-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20210524_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseoffer',
            name='status',
            field=models.CharField(choices=[('opened', 'opened'), ('waiting', 'waiting'), ('closed', 'closed')], default='opened', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleoffer',
            name='status',
            field=models.CharField(choices=[('opened', 'opened'), ('waiting', 'waiting'), ('closed', 'closed')], default='opened', max_length=7),
            preserve_default=False,
        ),
    ]
