# Generated by Django 3.1.11 on 2021-05-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20210524_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleoffer',
            name='suitable_offers',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='offers.purchaseoffer'),
            preserve_default=False,
        ),
    ]
