# Generated by Django 3.1.11 on 2021-05-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_auto_20210524_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseoffer',
            name='status',
            field=models.CharField(choices=[('opened', 'opened'), ('closed', 'closed')], default='opened', max_length=7),
        ),
        migrations.AlterField(
            model_name='saleoffer',
            name='status',
            field=models.CharField(choices=[('opened', 'opened'), ('closed', 'closed')], default='opened', max_length=7),
        ),
    ]
