# Generated by Django 3.1.11 on 2021-05-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_delete_item'),
        ('watchlists', '0005_auto_20210524_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='items',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='currencies',
            field=models.ManyToManyField(blank=True, null=True, related_name='currency', to='items.Currency'),
        ),
        migrations.DeleteModel(
            name='WatchlistItem',
        ),
    ]
