# Generated by Django 3.1.11 on 2021-05-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_delete_item'),
        ('watchlists', '0006_auto_20210524_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='currencies',
            field=models.ManyToManyField(blank=True, related_name='currency', to='items.Currency'),
        ),
    ]
