# Generated by Django 3.1.11 on 2021-05-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='money',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
