# Generated by Django 3.1.11 on 2021-05-24 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('opened', 'opened'), ('closed', 'closed')], max_length=6)),
                ('purchase_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.purchaseoffer')),
                ('sale_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.saleoffer')),
            ],
        ),
    ]
