# Generated by Django 3.1.11 on 2021-05-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='purchase_quantity_after_trade',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='purchase_quantity_before_trade',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='sale_quantity_after_trade',
            field=models.PositiveIntegerField(blank=True, default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='sale_quantity_before_trade',
            field=models.PositiveIntegerField(blank=True, default='1'),
            preserve_default=False,
        ),
    ]
