# Generated by Django 3.1.11 on 2021-05-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_auto_20210526_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('opened', 'opened'), ('closed', 'closed')], default='opened', max_length=6),
        ),
    ]
