# Generated by Django 3.1.11 on 2021-05-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
