# Generated by Django 3.1.11 on 2021-05-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210524_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='code',
            new_name='currency',
        ),
    ]
