# Generated by Django 3.1.11 on 2021-05-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210524_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
