# Generated by Django 3.1.11 on 2021-05-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_item_currency'),
        ('inventories', '0002_auto_20210524_0931'),
        ('offers', '0003_auto_20210524_0931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
